kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.name }}
  labels: 
    {{- include "labels" . | nindent 4 }}
    deployment: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        deployment: {{ .Values.name }}
        {{- if .Values.serviceMesh.enabled }}
        sidecar.istio.io/inject: "true"
        {{- end }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: {{ tpl .Values.image $ }}
          ports:
            - containerPort: 3000
              protocol: TCP
          imagePullPolicy: {{ .Values.imagePullPolicy | default "IfNotPresent" }}
          volumeMounts:
            - name: config-volume
              mountPath: /opt/app-root/src/public
            {{- .Values.resources | toYaml | nindent 12 }}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Values.name }}-config
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
