labels:
  app: chatbot-ui
  app.kubernetes.io/component: chatbot-ui
  app.kubernetes.io/instance: chatbot-ui
  app.kubernetes.io/name: chatbot-ui
  app.kubernetes.io/part-of: chatbot-application

name: chatbot-ui


image:  "chatbot-ui-patternfly:latest"
imagePullPolicy: Always

serviceMesh:
  enabled: false


resources:
  limits:
    cpu: 500m
    memory: 2Gi
  requests:
    cpu: 250m
    memory: 1Gi

backend:
  url: https://quarkus-llm-router-{{ .Release.Namespace }}.{{ .Values.clusterDomain }}/assistant/chat/streaming"