{{- range .Values.applications }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}-{{ .namespace | default $.Values.application.defaultNamespace }}
  labels:
    app.kubernetes.io/name: {{ .name }}
    app.kubernetes.io/instance-of: {{ $.Values.name }}
    app.kubernetes.io/managed-by: ArgoCD
    tenant: {{ $.Values.name }}
  namespace: {{ default $.Values.gitops.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "{{ .syncWave | default 0 }}"
spec:
  project: {{ $.Values.gitops.project | default "default" }}
  source:
    repoURL: {{ $.Values.repo.url }}
    targetRevision: {{ .branch | default $.Values.repo.branch }}
    path: {{ .path | default .name }}
    helm:
      valueFiles: 
        - {{ .valueFile | default $.Values.defaultValuesFile }}
      parameters:
        - name: clusterDomain
          value: {{ $.Values.clusterDomain }}
        {{- range .parameters }}
        - name: {{ .name }}
          value: {{ .value }}
        {{- end }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .namespace | default $.Values.application.defaultNamespace }}
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
  {{- if .ignoreDifferences }}
  ignoreDifferences:
    {{- toYaml .ignoreDifferences | nindent 4 }}
  {{- end }}
---
{{- end }}
