labels:
  app: kfp-pipelines
  app.kubernetes.io/component: kfp-pipelines
  app.kubernetes.io/instance: kfp-pipelines
  app.kubernetes.io/name: kfp-pipelines
  app.kubernetes.io/part-of: kfp-pipelines

dspa:
  minio:
    image: quay.io/minio/minio:RELEASE.2024-10-02T17-50-41Z
    pvcSize: 10Gi

defaults:
  git:
    url: 'https://github.com/sukantadash/data-ingestion.git'
    revision: 'main'
    path: 'kfp/redhat-product-documentation-ingestor'
    script: 'ingestion-pipeline-elastic.py'
    website_ingestion_path: 'kfp/redhat-product-documentation-ingestor'
    website_ingestion_script: 'ingestion-pipeline.py'
    website_ingestion_url: 'https://www.redhat.com/en/topics/containers/red-hat-openshift-okd'