labels:
  app: chatbot-ui
  app.kubernetes.io/component: chatbot-ui
  app.kubernetes.io/instance: chatbot-ui
  app.kubernetes.io/name: chatbot-ui
  app.kubernetes.io/part-of: chatbot-application

name: chatbot-ui

image: 'quay.io/redhat-composer-aicomposer-ai-studio:v0.1' # Update me
imagePullPolicy: Always

serviceMesh:
  enabled: false

repo:
  url: https://github.com/redhat-composer-ai/chatbot-ui.git
  branch: v2.2.0

resources:
  limits:
    cpu: 500m
    memory: 2Gi
  requests:
    cpu: 250m
    memory: 1Gi

backend:
  url: https://quarkus-llm-router-{{ .Release.Namespace }}.{{ .Values.clusterDomain }}/assistant/chat/streaming
  infoUrl: https://quarkus-llm-router-{{ .Release.Namespace }}.{{ .Values.clusterDomain }}/admin/assistant
  retrieverUrl: https://quarkus-llm-router-{{ .Release.Namespace }}.{{ .Values.clusterDomain }}/admin/assistant/retrieverConnection
  llmUrl: https://quarkus-llm-router-{{ .Release.Namespace }}.{{ .Values.clusterDomain }}/admin/assistant/llm
