labels:
  app: chatbot-ui
  app.kubernetes.io/component: chatbot-ui
  app.kubernetes.io/instance: chatbot-ui
  app.kubernetes.io/name: chatbot-ui
  app.kubernetes.io/part-of: chatbot-application

name: chatbot-ui

image: 'quay.io/redhat-composer-aicomposer-ai-studio:v0.2.3'
imagePullPolicy: Always

serviceMesh:
  enabled: false

resources:
  limits:
    cpu: 500m
    memory: 2Gi
  requests:
    cpu: 250m
    memory: 1Gi

backend:
  url: https://quarkus-llm-router-{{ .Release.Namespace }}.{{ .Values.clusterDomain }}
  streamingUrl: https://quarkus-llm-router-{{ .Release.Namespace }}.{{ .Values.clusterDomain }}/assistant/chat/streaming
  infoUrl: https://quarkus-llm-router-{{ .Release.Namespace }}.{{ .Values.clusterDomain }}/admin/assistant
  retrieverUrl: https://quarkus-llm-router-{{ .Release.Namespace }}.{{ .Values.clusterDomain }}/admin/assistant/retrieverConnection
  llmUrl: https://quarkus-llm-router-{{ .Release.Namespace }}.{{ .Values.clusterDomain }}/admin/assistant/llm

httpScheme: "http"
openid:
  enabled: false
  livenessProbe:
    enabled: true
    initialDelaySeconds: 0
    timeoutSeconds: 1
  readinessProbe:
    enabled: true
    initialDelaySeconds: 0
    timeoutSeconds: 5
    periodSeconds: 10
    successThreshold: 1
  config:
    provider: keycloak-oidc
    client_id: ""
    client_secret: ""
    redirect_url: ""
    oidc_issuer_url: ""
    email_domains: [] # Validate email domain for users, see option documentation
    upstreams: ["http://localhost:3000"]
    cookie_secret: ""
    code_challenge_method: "S256" # PKCE
  image:
    repository: "quay.io/oauth2-proxy/oauth2-proxy"
    # appVersion is used by default
    tag: "v7.7.1"
    pullPolicy: "IfNotPresent"
    command: []
    securityContext:
      enabled: true
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 2000
      runAsGroup: 2000
      seccompProfile:
        type: RuntimeDefault
  metrics:
    enabled: false
