kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.name }}
  labels: 
    {{- include "labels" . | nindent 4 }}
    deployment: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        deployment: {{ .Values.name }}
        {{- if .Values.serviceMesh.enabled }}
        sidecar.istio.io/inject: "true"
        {{- end }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.image }}
          ports:
            - containerPort: 5000
              protocol: TCP
          envFrom:
          - configMapRef:
              name: {{ .Values.name }}-config
          imagePullPolicy: {{ .Values.imagePullPolicy | default "IfNotPresent" }}
          resources:
            {{- .Values.resources | toYaml | nindent 12 }}
          env:
            - name: ELASTICSEARCH_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-es-elastic-user
                  key: elastic
            - name: QUARKUS_MONGODB_CONNECTION_STRING
              value: mongodb://mongodb-{{ .Release.Namespace }}:27017
            - name: QUARKUS_MONGODB_DATABASE
              value: composer
            - name: QUARKUS_MONGODB_CREDENTIALS_AUTH_SOURCE
              value: {{ .Values.mongodb.authSource }}
            - name: QUARKUS_MONGODB_CREDENTIALS_USERNAME
              value: {{ .Values.mongodb.username }}
            - name: QUARKUS_MONGODB_CREDENTIALS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ tpl .Values.mongodb.passwordSecret . }}
                  key: {{ .Values.mongodb.passwordKey }}
            - name: OPENAI_DEFAULT_URL
              value: {{ tpl .Values.openAIRuntime.url $ }}
            - name: OPENAI_DEFAULT_APIKEY
              value: {{ .Values.openAIRuntime.apikey }}
            - name: OPENAI_DEFAULT_MODELNAME
              value: {{ .Values.openAIRuntime.modelname }}
            - name: GOOGLE_CLIENT_ID
              value: {{ .Values.GOOGLE_CLIENT_ID | default "CLIENT_ID" }}
            - name: GOOGLE_CLIENT_SECRET
              value: {{ .Values.GOOGLE_CLIENT_SECRET | default "CLIENT_SECRET" }}
            - name: QUARKUS_LOG_LEVEL
              value: {{ .Values.logLevel | default "INFO" }}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
